spring:
  application:
    name: demo-worker1
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: demo-worker1-group
      auto-offset-reset: earliest

server:
  port: 8001

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
